# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - sutanto62 
  categories:
    - title: 🏕 Features
      labels:
        - '*'
      exclude:
        labels:
          - dependencies 
